(import ./actors)
(import ./enemies)
(import ./modes)
(import ./objects)
(import ./player)
(import ./startup)

(defn- run-game-timer!
  [ram]
  (def routine (get ram player/addr-game-routine))
  (when (and (= (get ram modes/oper-mode-address) modes/game)
             (= (get ram 0x0787) 0)
             (< (get ram player/addr-player-y-high) 2)
             (or (= routine 8) (= routine 9) (= routine 10) (= routine 12)))
    (def time (+ (* (get ram 0x07f8) 100)
                 (* (get ram 0x07f9) 10)
                 (get ram 0x07fa)))
    (when (pos? time)
      (def next-time (dec time))
      (put ram 0x0787 0x18)
      (put ram 0x07f8 (% (div next-time 100) 10))
      (put ram 0x07f9 (% (div next-time 10) 10))
      (put ram 0x07fa (% next-time 10)))))

(defn live-step
  [world]
  (def ram (world :ram))
  (def routine (get ram player/addr-game-routine))
  (case routine
    0 (player/entrance-setup! world)
    1 (player/vine-auto-climb! world)
    2 (player/side-pipe-entry! world)
    3 (player/vertical-pipe-entry! world)
    4 (player/flagpole-slide! world)
    5 (player/end-level! world)
    7 (player/entrance! world)
    8 (player/control! world)
    9 (player/change-size! world)
    10 (player/injury! world)
    11 (player/death! world)
    12 (player/fire-flower! world)
    (error (string "player routine is not ported: " routine)))
  (when (or (and (= (get ram modes/oper-mode-address) modes/title-screen)
                 (= (get ram modes/oper-mode-task-address) modes/title-game-menu))
            (and (= (get ram modes/oper-mode-address) modes/game)
                 (= (get ram modes/oper-mode-task-address) modes/game-core)))
    (objects/fireballs-bubbles! world)
    (loop [slot :range [0 actors/slot-count]]
      (def flag (get ram (+ actors/addr-enemy-flag slot)))
      (cond
        (not= (band flag 0x80) 0)
        (when (zero? (get ram (+ actors/addr-enemy-flag (band flag 0x0f))))
          (put ram (+ actors/addr-enemy-flag slot) 0))
        (not= flag 0)
        (objects/actor-slot! world slot)
        (not= (band (get ram 0x071f) 7) 7)
        (enemies/process-stream! world slot))
      (objects/floatey! world slot))
    (player/presentation-position! world)
    (player/graphics-step! world)
    (objects/update-block-metatiles! world)
    (objects/block! world 1)
    (objects/block! world 0)
    (objects/misc! world)
    (objects/cannons! world)
    (objects/whirlpools! world)
    (objects/flagpole! world)
    (run-game-timer! ram)
    (put ram player/addr-previous-a-b-buttons
         (get ram player/addr-a-b-buttons))
    (put ram player/addr-left-right-buttons 0)
    (startup/update-scroll-parser! world))
  world)
