(import spork/test)
(import ../../src/smb/actors)
(import ../../src/smb/modes)
(import ../../src/smb/oam)
(import ../../src/smb/objects)
(import ../../src/smb/player)
(import ../../src/smb/runtime)
(import ../../src/smb/startup)

(test/start-suite "World 1-2 block-hit lifecycle")

(defn- prepare-head-hit
  [tile size toggle]
  (def app (runtime/make-runtime))
  (def world (app :world))
  (def ram (world :ram))
  (put ram modes/oper-mode-address modes/game)
  (put ram modes/oper-mode-task-address modes/game-core)
  (put ram player/addr-game-routine player/routine-player-control)
  (put ram player/addr-area-type 2)
  (put ram player/addr-player-state player/state-jump-swim)
  (put ram player/addr-player-page 0)
  (put ram player/addr-player-x 0x80)
  (put ram player/addr-player-y-high 1)
  (put ram player/addr-player-y 0x84)
  (put ram player/addr-player-y-speed 0xfb)
  (put ram player/addr-player-size size)
  (put ram player/addr-player-crouching 0)
  (put ram player/addr-disable-collision 0)
  (put ram player/addr-swimming 0)
  (put ram player/addr-block-bounce-timer 0)
  (put ram player/addr-block-toggle toggle)
  (def mt-y (if (= size 0) 6 7))
  (def metatile-address (+ player/addr-block-buffer1 8 (* mt-y 16)))
  (put ram metatile-address tile)
  (player/background-collision! world)
  @{:app app
    :world world
    :ram ram
    :slot toggle
    :metatile-address metatile-address})

(def brick (prepare-head-hit 0x52 0 1))
(def brick-world (brick :world))
(def brick-ram (brick :ram))
(def brick-slot (brick :slot))
(test/assert (= (get brick-ram (+ 0x0026 brick-slot)) 0x12)
             "second block slot must preserve brick-shatter state 0x12")
(test/assert (= (get brick-ram (+ player/addr-block-y-high brick-slot)) 1)
             "brick chunks must inherit Mario's vertical page")
(test/assert (= (get brick-ram (brick :metatile-address)) 0x23)
             "an active block object must replace collision with the hit marker")
(test/assert (not= (get brick-ram 0x0301) 0)
             "block hit must queue its temporary blanking update")
(startup/consume-vram-buffer! brick-world)
(test/assert (and (= (get brick-ram 0x0300) 0)
                  (= (get brick-ram 0x0301) 0))
             "default NMI buffer selection must consume gameplay block updates")
(objects/update-block-metatiles! brick-world)
(test/assert (= (get brick-ram (brick :metatile-address)) 0)
             "a shattered brick must restore empty collision data")
(test/assert (= (get brick-ram (+ 0x03ec brick-slot)) 0)
             "brick metatile replacement must release its pending flag")
(loop [frame :range [0 192]
       :while (not= (get brick-ram (+ 0x0026 brick-slot)) 0)]
  (objects/block! brick-world brick-slot))
(test/assert (= (get brick-ram (+ 0x0026 brick-slot)) 0)
             "brick chunks must fall offscreen and release their block slot")

(def question (prepare-head-hit 0xc1 1 0))
(def question-world (question :world))
(def question-ram (question :ram))
(def question-slot (question :slot))
(test/assert (= (get question-ram (+ 0x0026 question-slot)) 0x11)
             "small Mario must bump an item block instead of shattering it")
(test/assert (= (get question-ram (+ player/addr-block-metatile question-slot)) 0xc4)
             "a used question block must restore as an empty block")
(test/assert (= (get question-ram (+ actors/addr-enemy-id 5)) actors/actor-power-up)
             "a power-up question block must populate fixed actor slot five")
(test/assert (= (get question-ram (+ actors/addr-enemy-flag 5)) 1)
             "spawned power-up actor must be active")
(test/assert (= (get question-ram actors/addr-power-up-type) 0)
             "small Mario must receive a mushroom from a power-up block")

(startup/consume-vram-buffer! question-world)
(loop [frame :range [0 96]
       :while (not= (get question-ram (+ 0x0026 question-slot)) 0)]
  (objects/block! question-world question-slot))
(test/assert (= (get question-ram (+ 0x0026 question-slot)) 0)
             "bumped question block must finish and release its block slot")
(objects/update-block-metatiles! question-world)
(test/assert (= (get question-ram (question :metatile-address)) 0xc4)
             "completed question block must become a used block")

(put question-ram (+ 0x06e5 5) 48)
(loop [frame :range [0 5]]
  (put question-ram actors/addr-frame-counter 0)
  (objects/actor-slot! question-world 5))
(test/assert (= (get question-ram (+ oam/data-base 49)) 0x76)
             "emerged mushroom must render its authentic upper-left tile")

(test/end-suite)
