(import spork/test)
(import ../../src/smb/actors)
(import ../../src/smb/area)
(import ../../src/smb/live-step)
(import ../../src/smb/modes)
(import ../../src/smb/objects)
(import ../../src/smb/player)
(import ../../src/smb/runtime)

(test/start-suite "flagpole and World 1-1 end-level flow")

(def idle-app (runtime/make-runtime))
(def idle-world (idle-app :world))
(def idle-ram (idle-world :ram))
(put idle-ram actors/addr-enemy-flag 1)
(put idle-ram actors/addr-enemy-id actors/actor-star-flag)
(put idle-ram 0x0746 0)
(objects/actor-slot! idle-world 0)
(test/assert (= (get idle-ram actors/addr-enemy-flag) 1)
             "an idle castle star flag must remain active without dispatch failure")
(test/assert (= (get idle-ram 0x0746) 0)
             "an idle castle star flag must wait for Mario's level-end walk")

(def timer-app (runtime/make-runtime))
(def timer-world (timer-app :world))
(def timer-ram (timer-world :ram))
(put timer-ram modes/oper-mode-address modes/game)
(put timer-ram actors/addr-enemy-flag 1)
(put timer-ram actors/addr-enemy-id actors/actor-star-flag)
(put timer-ram 0x0746 2)
(put timer-ram 0x07f8 0)
(put timer-ram 0x07f9 0)
(put timer-ram 0x07fa 1)
(objects/actor-slot! timer-world 0)
(test/assert (= (get timer-ram 0x07fa) 0)
             "castle timer award must decrement the visible timer")
(test/assert (= (get timer-ram 0x07e2) 5)
             "each remaining timer unit must award fifty score points")
(objects/actor-slot! timer-world 0)
(test/assert (= (get timer-ram 0x0746) 3)
             "depleted castle timer must advance to flag raising")

(def app (runtime/make-runtime))
(def world (app :world))
(def ram (world :ram))
(put ram modes/oper-mode-address modes/game)
(put ram modes/oper-mode-task-address modes/game-core)
(put ram player/addr-game-routine player/routine-player-end-level)
(put ram area/disable-screen-address 0)
(put ram player/addr-player-state player/state-on-ground)
(put ram player/addr-player-facing player/button-right)
(put ram player/addr-player-moving player/button-right)
(put ram player/addr-player-y-high 0)
(put ram player/addr-player-y 0xae)
(put ram player/addr-player-x 0x90)
(put ram player/addr-collision-bits 0)
(put ram player/addr-scroll-lock 1)
(put ram player/addr-screen-left-x 0)
(put ram player/addr-screen-right-x 0xff)
(put ram area/area-parser-task-address 7)
(put ram actors/addr-enemy-flag 1)
(put ram actors/addr-enemy-id actors/actor-star-flag)
(put ram actors/addr-enemy-page 0)
(put ram actors/addr-enemy-x 0xd0)
(put ram actors/addr-enemy-y-high 1)
(put ram actors/addr-enemy-y 0x71)
(put ram 0x07f8 0)
(loop [slot :range [1 actors/slot-count]]
  (put ram (+ actors/addr-enemy-flag slot) 0x80))
(put ram 0x07f9 0)
(put ram 0x07fa 0)

(live-step/live-step world)
(test/assert (= (get ram 0x0746) 2)
             "castle star flag must start after Mario reaches the door")
(test/assert (= (get ram player/addr-scroll-lock) 0)
             "level-end walk must release the flagpole scroll lock")

(live-step/live-step world)
(test/assert (= (get ram 0x0746) 3)
             "zero game timer must advance directly to flag raising")

(live-step/live-step world)
(test/assert (= (get ram 0x0746) 4)
             "raised flag without fireworks must enter the area-end delay")
(put ram 0x0796 0)
(live-step/live-step world)
(test/assert (= (get ram 0x0746) 5)
             "elapsed area-end delay must complete the star-flag task")
(put ram area/area-parser-task-address 4)

(live-step/live-step world)
(test/assert (= (get ram 0x075c) 1)
             "World 1-1 completion must advance the level number")
(test/assert (= (get ram 0x0760) 1)
             "World 1-1 completion must advance to the next area pointer")
(test/assert (= (get ram modes/oper-mode-task-address) modes/game-initialize-area)
             "World 1-1 completion must restart through area initialization")
(test/assert (= (get ram area/disable-screen-address) 1)
             "next-area transition must disable presentation")
(test/assert (= (get ram area/area-parser-task-address) 4)
             "game core must stop immediately after NextArea changes the mode task")

(def fireworks-app (runtime/make-runtime))
(def fireworks-world (fireworks-app :world))
(def fireworks-ram (fireworks-world :ram))
(put fireworks-ram actors/addr-enemy-flag 1)
(put fireworks-ram modes/oper-mode-address modes/game)
(put fireworks-ram actors/addr-enemy-id actors/actor-star-flag)
(put fireworks-ram actors/addr-enemy-page 1)
(put fireworks-ram actors/addr-enemy-x 0xd0)
(put fireworks-ram actors/addr-enemy-state 5)
(put fireworks-ram 0x06d7 1)
(put fireworks-ram 0x078f 0)
(put fireworks-ram (+ actors/addr-enemy-id 1) actors/actor-fireworks)
(actors/initialize! fireworks-world 1)
(test/assert (= (get fireworks-ram (+ actors/addr-enemy-flag 1)) 1)
             "fireworks frenzy must initialize a visible explosion actor")
(test/assert (= (get fireworks-ram (+ actors/addr-enemy-y-speed 1)) 8)
             "fireworks explosion must initialize its eight-frame phase timer")
(objects/actor-slot! fireworks-world 1)
(test/assert (= (get fireworks-ram (+ actors/addr-enemy-flag 1)) 1)
             "active fireworks must render without special-actor dispatch failure")

(loop [frame :range [0 23]]
  (objects/actor-slot! fireworks-world 1))
(test/assert (= (get fireworks-ram (+ actors/addr-enemy-flag 1)) 0)
             "finished fireworks must release their actor slot")
(test/assert (= (get fireworks-ram 0x00fe) 8)
             "finished fireworks must queue the kaboom sound")
(test/assert (= (get fireworks-ram 0x07e1) 5)
             "finished fireworks must award five hundred score points")
(test/end-suite)
