(import spork/test)
(import ../../src/smb/actors)
(import ../../src/smb/area)
(import ../../src/smb/input)
(import ../../src/smb/modes)
(import ../../src/smb/rom)
(import ../../src/smb/runtime)
(import ../../src/smb/movement)

(test/start-suite "authentic startup and hot redefinition preserve running state")

(def app (runtime/make-runtime))
(runtime/reload-step! app)
(def stable-world (app :world))
(def stable-display (app :presentation))
(def stable-sound (app :sound))
(def stable-ram (stable-world :ram))
(test/assert (not (stable-display :screen-on))
             "cold boot must begin with presentation disabled")
(test/assert (= (stable-display :command-count) 0)
             "cold boot must not emit visible tiles")

(loop [_ :range [0 30]]
  (runtime/tick! app 0))
(test/assert (= (get stable-ram modes/oper-mode-address) modes/title-screen)
             "boot must enter title-screen mode")
(test/assert (= (get stable-ram modes/oper-mode-task-address) modes/title-game-menu)
             "boot must reach the interactive title menu")
(test/assert (stable-display :screen-on)
             "title menu must enable the SMB tile surface")
(test/assert (= (stable-display :command-count) 1856)
             "title menu must build the complete background and OAM command stream")

(def frame-before (stable-world :frame))
(def old-step (app :step))
(put stable-ram 0x47c 0xa5)
(runtime/reload-step! app)

(test/assert (= stable-world (app :world))
             "reload must retain the world table")
(test/assert (= stable-ram ((app :world) :ram))
             "reload must retain the gameplay RAM buffer")
(test/assert (= stable-display (app :presentation))
             "reload must retain presentation buffers and texture-independent state")
(test/assert (= stable-sound (app :sound))
             "reload must retain isolated sound-engine presentation state")
(test/assert (not= old-step (app :step))
             "reload must install a newly compiled frame function")
(test/assert (= (app :reload-generation) 2)
             "reload generation must advance")
(test/assert (= (app :last-reload-frame) frame-before)
             "reload must occur at a frame boundary")
(test/assert (= ((app :world) :frame) frame-before)
             "reload must not advance or reset simulation time")
(test/assert (= (get stable-ram 0x47c) 0xa5)
             "unrelated gameplay RAM must survive reload")

(runtime/tick! app 0)
(test/assert (= ((app :world) :frame) (inc frame-before))
             "new frame function must continue from the same title-menu boundary")
(test/assert (= (get stable-ram 0x47c) 0xa5)
             "title-menu execution must retain unrelated RAM")

(runtime/tick! app input/button-start)
(test/assert (= (get stable-ram modes/oper-mode-address) modes/game)
             "Start must select game mode")
(test/assert (= (get stable-ram modes/oper-mode-task-address) modes/game-initialize-area)
             "Start must route through area initialization")

(var startup-frames 0)
(while (and (not= (get stable-ram modes/oper-mode-task-address) modes/game-core)
            (< startup-frames 300))
  (runtime/tick! app 0)
  (++ startup-frames))
(test/assert (< startup-frames 300)
             "World 1-1 screen construction must reach game core")
(runtime/tick! app 0)
(runtime/tick! app 0)

(def x-before (get stable-ram movement/x-position-base))
(loop [_ :range [0 30]]
  (runtime/tick! app (bor input/button-b input/button-right)))
(test/assert (not= (get stable-ram movement/x-position-base) x-before)
             "World 1-1 game core must advance Mario under controller input")

(put stable-ram actors/addr-enemy-flag 1)
(put stable-ram actors/addr-enemy-id actors/actor-goomba)
(put stable-ram actors/addr-enemy-page
     (get stable-ram movement/page-base))
(put stable-ram actors/addr-enemy-x 0x90)
(put stable-ram actors/addr-enemy-y-high 1)
(put stable-ram actors/addr-enemy-y 0x80)
(actors/initialize! stable-world 0)
(def actor-x-before (get stable-ram actors/addr-enemy-x))
(runtime/tick! app 0)
(test/assert (not= (get stable-ram actors/addr-enemy-x) actor-x-before)
             "game core must advance active actor slots")
(test/assert (= (get stable-ram actors/addr-enemy-flag) 1)
             "onscreen actor must remain active after processing")

(put stable-ram 0x0756 2)
(put stable-ram actors/addr-fireball-state 0)
(put stable-ram 0x06ce 0)
(runtime/tick! app input/button-b)
(test/assert (not= (get stable-ram actors/addr-fireball-state) 0)
             "game core must process fireball creation before actor slots")

(def area-app (runtime/make-runtime (rom/load)))
(def area-world (area-app :world))
(def area-ram (area-world :ram))
(put area-ram area/world-number-address 0)
(put area-ram area/area-number-address 0)
(area/load-pointer! area-world)
(put area-ram modes/oper-mode-address modes/game)
(put area-ram modes/oper-mode-task-address modes/game-initialize-area)
(modes/dispatch! area-world (area-app :mode-handlers))
(test/assert (= (get area-ram modes/oper-mode-task-address)
                modes/game-screen-routines)
             "runtime area initialization must advance to screen routines")
(test/assert (= (get area-ram area/disable-screen-address) 1)
             "runtime area initialization must disable presentation")
(test/assert (not= (area/data-address area-ram) 0)
             "runtime area initialization must resolve the area stream")
(test/end-suite)
