(import spork/test)
(import ../../src/smb/actors)
(import ../../src/smb/area)
(import ../../src/smb/modes)
(import ../../src/smb/player)
(import ../../src/smb/runtime)
(import ../../src/smb/scroll)
(import ../../src/smb/victory)

(test/start-suite "castle axe victory and next-world transition")

(def app (runtime/make-runtime))
(def world (app :world))
(def ram (world :ram))
(put ram 0x071f 7)

(put ram modes/oper-mode-address modes/victory)
(put ram modes/oper-mode-task-address modes/victory-bridge-collapse)
(loop [slot :range [0 5]]
  (put ram (+ actors/addr-enemy-flag slot) 1)
  (put ram (+ actors/addr-enemy-id slot) actors/actor-goomba))
(victory/bridge-collapse! world)
(test/assert (= (get ram modes/oper-mode-task-address) modes/victory-setup)
             "an absent Bowser must complete bridge collapse")
(test/assert (= (get ram victory/addr-event-music) 0x80)
             "completed bridge collapse must stop event music")
(loop [slot :range [0 5]]
  (test/assert (zero? (get ram (+ actors/addr-enemy-flag slot)))
               "bridge completion must erase every normal actor slot"))

(put ram scroll/screen-right-page-address 7)
(victory/setup! world)
(test/assert (= (get ram victory/addr-victory-destination-page) 8)
             "victory setup must target the page after the visible castle")
(test/assert (= (get ram victory/addr-event-music) 8)
             "victory setup must queue the Bowser-victory music")
(test/assert (= (get ram modes/oper-mode-task-address) modes/victory-player-walk)
             "victory setup must advance to the automatic walk")

(put ram modes/oper-mode-task-address modes/victory-player-walk)
(put ram victory/addr-victory-destination-page 8)
(put ram player/addr-player-page 8)
(put ram player/addr-player-x 0x60)
(put ram scroll/screen-left-page-address 8)
(victory/player-walk! world)
(test/assert (= (get ram modes/oper-mode-task-address)
                modes/victory-print-messages)
             "Mario at the destination must finish the automatic victory walk")

(put ram modes/oper-mode-task-address modes/victory-bridge-collapse)
(put ram victory/addr-bowser-front-offset 0)
(put ram 0x06cf 1)
(put ram actors/addr-enemy-flag 1)
(put ram actors/addr-enemy-id actors/actor-bowser)
(put ram actors/addr-enemy-state 0)
(put ram actors/addr-enemy-y 0x70)
(put ram victory/addr-bowser-feet-counter 1)
(put ram victory/addr-bridge-collapse-offset 0)
(put ram victory/addr-vram-buffer-offset 0)
(victory/bridge-collapse! world)
(test/assert (= (get ram victory/addr-bridge-collapse-offset) 1)
             "Bowser footfall must remove one bridge metatile")
(test/assert (= (get ram victory/addr-vram-buffer-offset) 10)
             "bridge removal must append one two-row VRAM packet")
(test/assert (= (get ram 0x0301) 0x22)
             "first bridge packet must address castle nametable row")
(test/assert (= (get ram 0x0303) 2)
             "bridge packet must replace two horizontal tiles")
(test/assert (= (get ram 0x0304) 0x24)
             "bridge packet must replace the metatile with blanks")
(test/assert (= (get ram modes/oper-mode-task-address)
                modes/victory-bridge-collapse)
             "active Bowser must keep bridge collapse running")

(put ram actors/addr-enemy-state 0)
(put ram victory/addr-bowser-feet-counter 1)
(put ram victory/addr-bridge-collapse-offset 14)
(victory/bridge-collapse! world)
(test/assert (= (get ram victory/addr-bridge-collapse-offset) 15)
             "last bridge metatile must complete the collapse")
(test/assert (= (get ram actors/addr-enemy-state) 0x40)
             "completed bridge removal must start Bowser's fall")
(test/assert (= (get ram victory/addr-square2-sound) 0x80)
             "completed bridge removal must queue Bowser's fall sound")

(put ram actors/addr-enemy-y 0xdf)
(put ram actors/addr-enemy-y-speed 0)
(put ram actors/addr-enemy-y-force 0)
(victory/bridge-collapse! world)
(test/assert (= (get ram actors/addr-enemy-y-force) 0x0f)
             "falling Bowser must accelerate below the bridge")
(test/assert (= (get ram modes/oper-mode-task-address)
                modes/victory-bridge-collapse)
             "Bowser's fall must finish before victory setup")

(put ram actors/addr-enemy-y 0xe0)
(victory/bridge-collapse! world)
(test/assert (= (get ram modes/oper-mode-task-address) modes/victory-setup)
             "Bowser below the screen must complete bridge collapse")
(test/assert (zero? (get ram actors/addr-enemy-flag))
             "completed bridge collapse must erase Bowser")

(put ram modes/oper-mode-task-address modes/victory-print-messages)
(put ram victory/addr-primary-message-counter 0)
(put ram victory/addr-secondary-message-counter 0)
(put ram victory/addr-current-player 0)
(put ram victory/addr-world-number 0)
(victory/print-messages! world)
(test/assert (= (get ram victory/addr-vram-address-control) 12)
             "World 1 victory must select the Mario thank-you message")
(test/assert (= (get ram victory/addr-secondary-message-counter) 4)
             "victory message counter must advance four ticks per frame")

(put ram victory/addr-primary-message-counter 4)
(put ram victory/addr-secondary-message-counter 0)
(victory/print-messages! world)
(test/assert (= (get ram victory/addr-world-end-timer) 6)
             "World 1 message completion must arm the end-world timer")
(test/assert (= (get ram modes/oper-mode-task-address)
                modes/victory-player-end-world)
             "completed messages must advance to end-world handling")

(put ram victory/addr-world-end-timer 0)
(put ram area/area-pointer-address 0xff)
(put ram victory/addr-world-number 0)
(put ram victory/addr-area-number 3)
(put ram victory/addr-level-number 3)
(put ram victory/addr-fetch-new-game-timer 0)
(victory/player-end-world! world)
(test/assert (= (get ram victory/addr-world-number) 1)
             "World 1 completion must select World 2")
(test/assert (zero? (get ram victory/addr-area-number))
             "World 2 must start at its first area")
(test/assert (zero? (get ram victory/addr-level-number))
             "World 2 must start at level index zero")
(test/assert (= (get ram victory/addr-fetch-new-game-timer) 1)
             "World 2 initialization must request a fresh game timer")
(test/assert (= (get ram modes/oper-mode-address) modes/game)
             "World 2 transition must return to game mode")
(test/assert (= (get ram modes/oper-mode-task-address) modes/game-initialize-area)
             "World 2 transition must initialize its area")
(test/assert (not= (get ram area/area-pointer-address) 0xff)
             "World 2 transition must select its first area pointer")

(test/end-suite)
